spring: 
  application:
    name: ORGANIZATION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/organization
    username: organization
    password: organization
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #Hibernate cria automaticamente as tabelas
    open-in-view: false #Best practice in modern Spring Boot apps (especially REST APIs) is to set spring.jpa.open-in-view=false and fetch all required data in the service layer.
server:
  port: 8083

